package com.panadi.ums.studentservice;

import com.panadi.ums.studentservice.application.ApplicationException;
import com.panadi.ums.studentservice.application.PageResult;
import com.panadi.ums.studentservice.application.ResourceNotFoundException;
import com.panadi.ums.studentservice.application.command.StudentCommand;
import com.panadi.ums.studentservice.application.port.in.StudentUseCase;
import com.panadi.ums.studentservice.application.port.out.AcademicProgramValidationPort;
import com.panadi.ums.studentservice.domain.model.Gender;
import com.panadi.ums.studentservice.domain.model.Student;
import com.panadi.ums.studentservice.domain.model.StudentStatus;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.testcontainers.service.connection.ServiceConnection;
import org.springframework.security.oauth2.jwt.JwtDecoder;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.bean.override.mockito.MockitoBean;
import org.springframework.transaction.annotation.Transactional;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

import java.time.LocalDate;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * Integration test for the student-service persistence and business logic stack.
 *
 * <h2>Architecture</h2>
 * <ul>
 *   <li>A real PostgreSQL container (via Testcontainers) runs Flyway migrations,
 *       ensuring the schema and indexes are exactly what production uses.</li>
 *   <li>{@link AcademicProgramValidationPort} is mocked so the test has no
 *       dependency on academic-service.</li>
 *   <li>{@link JwtDecoder} is mocked so the security auto-configuration can
 *       load without a running Keycloak server.</li>
 *   <li>{@code @Transactional} on this class makes Spring roll back every test
 *       automatically — no manual cleanup required.</li>
 * </ul>
 *
 * <h2>What is exercised</h2>
 * The test calls through the full application stack:
 * {@code REST request → StudentUseCase → StudentService → StudentPersistenceAdapter
 *     → StudentJpaRepository → PostgreSQL (Testcontainers)}.
 */
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.NONE)
@ActiveProfiles("test")
@Testcontainers
@Transactional // each @Test rolls back — free isolation, no cleanup boilerplate
class StudentServiceIntegrationTest {

    // ─── Infrastructure ───────────────────────────────────────────────────────

    /**
     * Shared PostgreSQL container, started once per test class.
     * {@code @ServiceConnection} registers auto-configuration overrides that
     * point {@code spring.datasource.*} at the container's ephemeral URL/port,
     * overriding any static datasource config.
     */
    @Container
    @ServiceConnection
    static final PostgreSQLContainer<?> postgres =
            new PostgreSQLContainer<>("postgres:17");

    /**
     * Mocked so {@code SecurityAutoConfiguration}'s {@code @ConditionalOnMissingBean}
     * check finds a {@code JwtDecoder} already present and skips creating the
     * real {@link org.springframework.security.oauth2.jwt.NimbusJwtDecoder},
     * which would otherwise try to reach the placeholder Keycloak URI.
     */
    @MockitoBean
    JwtDecoder jwtDecoder;

    /**
     * Mocked to decouple student-service tests from academic-service.
     * The default void-returning mock does nothing, simulating a valid,
     * active program for every {@code programId} provided.
     */
    @MockitoBean
    AcademicProgramValidationPort academicPrograms;

    @Autowired
    StudentUseCase studentUseCase;

    // Stable programId reused across helpers — the mock validates it unconditionally
    private static final UUID PROGRAM_ID = UUID.fromString("00000000-0000-0000-0000-000000000001");

    // ─── Creation & Retrieval ─────────────────────────────────────────────────

    @Nested
    @DisplayName("createStudent / getStudent")
    class CreationAndRetrieval {

        @Test
        @DisplayName("persists student and retrieves it by id with all fields intact")
        void shouldPersistAndRetrieveById() {
            StudentCommand cmd = command("STU-001", "alice@test.com");

            Student created = studentUseCase.createStudent(cmd);

            assertThat(created.id()).as("id should be generated by the DB").isNotNull();
            assertThat(created.status()).isEqualTo(StudentStatus.ACTIVE);
            assertThat(created.studentCode()).isEqualTo("STU-001");
            assertThat(created.programId()).isEqualTo(PROGRAM_ID);

            // Second round-trip: verify the row was actually written
            Student fetched = studentUseCase.getStudent(created.id());
            assertThat(fetched.id()).isEqualTo(created.id());
            assertThat(fetched.firstName()).isEqualTo("Alice");
            assertThat(fetched.lastName()).isEqualTo("Smith");
            assertThat(fetched.email()).isEqualTo("alice@test.com");
            assertThat(fetched.dateOfBirth()).isEqualTo(LocalDate.of(2000, 6, 15));
            assertThat(fetched.admissionDate()).isEqualTo(LocalDate.of(2024, 9, 1));
        }

        @Test
        @DisplayName("retrieves student by Keycloak userId")
        void shouldFindByUserId() {
            UUID userId = UUID.randomUUID();
            Student created = studentUseCase.createStudent(commandForUser(userId, "STU-002", "bob@test.com"));

            Student found = studentUseCase.getStudentByUserId(userId);

            assertThat(found.id()).isEqualTo(created.id());
            assertThat(found.userId()).isEqualTo(userId);
        }

        @Test
        @DisplayName("throws ResourceNotFoundException for an unknown id")
        void shouldThrowForUnknownId() {
            assertThatThrownBy(() -> studentUseCase.getStudent(UUID.randomUUID()))
                    .isInstanceOf(ResourceNotFoundException.class)
                    .hasMessage("Student not found");
        }
    }

    // ─── Status Lifecycle ─────────────────────────────────────────────────────

    @Nested
    @DisplayName("Status transitions")
    class StatusLifecycle {

        @Test
        @DisplayName("full lifecycle: ACTIVE → INACTIVE → SUSPENDED → ACTIVE persists each step")
        void shouldPersistStatusTransitions() {
            Student student = studentUseCase.createStudent(command("STU-003", "carol@test.com"));
            assertThat(student.status()).isEqualTo(StudentStatus.ACTIVE);

            // deactivate
            Student deactivated = studentUseCase.deactivateStudent(student.id());
            assertThat(deactivated.status()).isEqualTo(StudentStatus.INACTIVE);
            // verify the DB row was updated (not just the in-memory object)
            assertThat(studentUseCase.getStudent(student.id()).status())
                    .isEqualTo(StudentStatus.INACTIVE);

            // suspend
            Student suspended = studentUseCase.suspendStudent(student.id());
            assertThat(suspended.status()).isEqualTo(StudentStatus.SUSPENDED);

            // reactivate
            Student reactivated = studentUseCase.activateStudent(student.id());
            assertThat(reactivated.status()).isEqualTo(StudentStatus.ACTIVE);
        }
    }

    // ─── Listing & Filtering ──────────────────────────────────────────────────

    @Nested
    @DisplayName("listStudents")
    class Listing {

        @Test
        @DisplayName("filters by status: only ACTIVE students returned when status=ACTIVE")
        void shouldFilterByStatus() {
            studentUseCase.createStudent(commandForUser(UUID.randomUUID(), "STU-ACT", "act@test.com"));
            Student toDeactivate = studentUseCase.createStudent(
                    commandForUser(UUID.randomUUID(), "STU-INC", "inc@test.com"));
            studentUseCase.deactivateStudent(toDeactivate.id());

            PageResult<Student> activeOnly = studentUseCase.listStudents(StudentStatus.ACTIVE, null, 0, 20);

            assertThat(activeOnly.content())
                    .extracting(Student::studentCode)
                    .contains("STU-ACT")
                    .doesNotContain("STU-INC");
            assertThat(activeOnly.content())
                    .extracting(Student::status)
                    .allMatch(s -> s == StudentStatus.ACTIVE);
        }

        @Test
        @DisplayName("filters by programId: only students in the given program returned")
        void shouldFilterByProgramId() {
            UUID otherProgram = UUID.randomUUID();

            studentUseCase.createStudent(commandForUser(UUID.randomUUID(), "STU-P1", "p1@test.com")); // PROGRAM_ID
            studentUseCase.createStudent(commandForUser(UUID.randomUUID(), "STU-P2", "p2@test.com",
                    otherProgram)); // different program

            PageResult<Student> results = studentUseCase.listStudents(null, PROGRAM_ID, 0, 20);

            assertThat(results.content())
                    .extracting(Student::studentCode)
                    .contains("STU-P1")
                    .doesNotContain("STU-P2");
        }

        @Test
        @DisplayName("pagination metadata is correct")
        void shouldReturnCorrectPaginationMetadata() {
            for (int i = 0; i < 5; i++) {
                studentUseCase.createStudent(
                        commandForUser(UUID.randomUUID(), "PAGE-" + i, "page" + i + "@test.com"));
            }

            PageResult<Student> page = studentUseCase.listStudents(null, null, 0, 3);

            assertThat(page.size()).isEqualTo(3);
            assertThat(page.content()).hasSize(3);
            assertThat(page.totalElements()).isGreaterThanOrEqualTo(5);
            assertThat(page.totalPages()).isGreaterThanOrEqualTo(2);
        }
    }

    // ─── Uniqueness Constraints ───────────────────────────────────────────────

    @Nested
    @DisplayName("Uniqueness enforcement")
    class UniquenessConstraints {

        @Test
        @DisplayName("rejects duplicate student code")
        void shouldRejectDuplicateStudentCode() {
            studentUseCase.createStudent(commandForUser(UUID.randomUUID(), "DUP-CODE", "first@test.com"));

            assertThatThrownBy(() ->
                    studentUseCase.createStudent(commandForUser(UUID.randomUUID(), "DUP-CODE", "other@test.com")))
                    .isInstanceOf(ApplicationException.class)
                    .hasMessage("Student code already exists");
        }

        @Test
        @DisplayName("rejects duplicate email address")
        void shouldRejectDuplicateEmail() {
            studentUseCase.createStudent(commandForUser(UUID.randomUUID(), "STU-E1", "dup@test.com"));

            assertThatThrownBy(() ->
                    studentUseCase.createStudent(commandForUser(UUID.randomUUID(), "STU-E2", "dup@test.com")))
                    .isInstanceOf(ApplicationException.class)
                    .hasMessage("Student email already exists");
        }

        @Test
        @DisplayName("rejects duplicate Keycloak userId (one user = one student profile)")
        void shouldRejectDuplicateUserId() {
            UUID sharedUser = UUID.randomUUID();
            studentUseCase.createStudent(commandForUser(sharedUser, "STU-U1", "u1@test.com"));

            assertThatThrownBy(() ->
                    studentUseCase.createStudent(commandForUser(sharedUser, "STU-U2", "u2@test.com")))
                    .isInstanceOf(ApplicationException.class)
                    .hasMessage("Keycloak user is already linked to another student profile");
        }

        @Test
        @DisplayName("updateStudent allows keeping same code / email on the same record")
        void shouldAllowSameCodeOnUpdate() {
            Student student = studentUseCase.createStudent(
                    commandForUser(UUID.randomUUID(), "STU-UPD", "upd@test.com"));

            // Updating with the same studentCode / email should not throw
            StudentCommand updateCmd = new StudentCommand(
                    student.userId(), student.studentCode(), "Updated", "Name",
                    Gender.MALE, LocalDate.of(1999, 1, 1),
                    student.email(), "+9999", "New Address",
                    PROGRAM_ID, LocalDate.of(2024, 9, 1));

            Student updated = studentUseCase.updateStudent(student.id(), updateCmd);

            assertThat(updated.firstName()).isEqualTo("Updated");
            assertThat(updated.studentCode()).isEqualTo("STU-UPD");
        }
    }

    // ─── Helpers ─────────────────────────────────────────────────────────────

    private StudentCommand command(String code, String email) {
        return commandForUser(UUID.randomUUID(), code, email, PROGRAM_ID);
    }

    private StudentCommand commandForUser(UUID userId, String code, String email) {
        return commandForUser(userId, code, email, PROGRAM_ID);
    }

    private StudentCommand commandForUser(UUID userId, String code, String email, UUID programId) {
        return new StudentCommand(
                userId,
                code,
                "Alice",
                "Smith",
                Gender.FEMALE,
                LocalDate.of(2000, 6, 15),   // 24 years old — satisfies the ≥17 domain rule
                email,
                "+1-555-0100",
                "42 University Ave",
                programId,
                LocalDate.of(2024, 9, 1)
        );
    }
}
